// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Restier.Samples.Postgres.AspNetCore.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microsoft.Restier.Samples.Postgres.AspNetCore.Migrations
{
    [DbContext(typeof(RestierTestContext))]
    [Migration("20260419073442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.Restier.Samples.Postgres.AspNetCore.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Users_Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000001"),
                            EmailAddress = "admin@example.com",
                            UserTypeId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000002"),
                            EmailAddress = "editor@example.com",
                            UserTypeId = new Guid("a1b2c3d4-0001-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000003"),
                            EmailAddress = "viewer@example.com",
                            UserTypeId = new Guid("a1b2c3d4-0001-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000004"),
                            EmailAddress = "another.admin@example.com",
                            UserTypeId = new Guid("a1b2c3d4-0001-0001-0001-000000000001")
                        });
                });

            modelBuilder.Entity("Microsoft.Restier.Samples.Postgres.AspNetCore.Models.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id")
                        .HasName("PK_UserTypes_Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Administrator",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Editor",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Viewer",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Microsoft.Restier.Samples.Postgres.AspNetCore.Models.User", b =>
                {
                    b.HasOne("Microsoft.Restier.Samples.Postgres.AspNetCore.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .HasConstraintName("FK_Users_UserTypes");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Microsoft.Restier.Samples.Postgres.AspNetCore.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
