// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.Restier.Core.Spatial;
using Microsoft.Spatial;
using NetTopologySuite.Geometries;

namespace Microsoft.Restier.Samples.Postgres.AspNetCore.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string EmailAddress { get; set; }

    [Spatial(typeof(GeographyPoint))]
    public Point HomeLocation { get; set; }

    public Guid? UserTypeId { get; set; }

    public virtual UserType UserType { get; set; }
}