// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Microsoft.Restier.Samples.Postgres.AspNetCore.Models;

public partial class UserType
{
    public Guid Id { get; set; }

    public string DisplayName { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}