@Microsoft.Restier.Samples.Northwind.AspNetCore.OData_HostAddress = http://localhost:5295

GET {{Microsoft.Restier.Samples.Northwind.AspNetCore.OData_HostAddress}}/weatherforecast/
Accept: application/json

###
