//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 9/24/2014 8:29:49 AM
namespace System.Web.OData.Domain.Test.Services.Trippin.Models
{
    /// <summary>
    /// There are no comments for TrippinModel in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TrippinModel")]
    public partial class TrippinModel : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TrippinModel object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public TrippinModel(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline", "System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "System.Web.OData.Domain.Test.Services.Trippin.Models", "System.Web.OData.Domain.Test.Services.Trippin.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline.", originalNameAttribute.OriginalName);
                }
                return string.Concat("System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline.", clientType.Name);
            }
            if (clientType.Namespace.Equals("System.Web.OData.Domain.Test.Services.Trippin.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("System.Web.OData.Domain.Test.Services.Trippin.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("System.Web.OData.Domain.Test.Services.Trippin.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Airlines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Airline> Airlines
        {
            get
            {
                if ((this._Airlines == null))
                {
                    this._Airlines = base.CreateQuery<Airline>("Airlines");
                }
                return this._Airlines;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Airline> _Airlines;
        /// <summary>
        /// There are no comments for Airports in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Airport> Airports
        {
            get
            {
                if ((this._Airports == null))
                {
                    this._Airports = base.CreateQuery<Airport>("Airports");
                }
                return this._Airports;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Airport> _Airports;
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Flight> Flights
        {
            get
            {
                if ((this._Flights == null))
                {
                    this._Flights = base.CreateQuery<Flight>("Flights");
                }
                return this._Flights;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Flight> _Flights;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<Person>("People");
                }
                return this._People;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Person> _People;
        /// <summary>
        /// There are no comments for Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Trip> Trips
        {
            get
            {
                if ((this._Trips == null))
                {
                    this._Trips = base.CreateQuery<Trip>("Trips");
                }
                return this._Trips;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Trip> _Trips;
        /// <summary>
        /// There are no comments for Airlines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToAirlines(Airline airline)
        {
            base.AddObject("Airlines", airline);
        }
        /// <summary>
        /// There are no comments for Airports in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToAirports(Airport airport)
        {
            base.AddObject("Airports", airport);
        }
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToFlights(Flight flight)
        {
            base.AddObject("Flights", flight);
        }
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
        /// <summary>
        /// There are no comments for Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToTrips(Trip trip)
        {
            base.AddObject("Trips", trip);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""System.Web.OData.Domain.Test.Services.Trippin.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Airline"">
        <Key>
          <PropertyRef Name=""AirlineCode"" />
        </Key>
        <Property Name=""AirlineCode"" Type=""Edm.String"" Nullable=""false"" MaxLength=""128"" />
        <Property Name=""Name"" Type=""Edm.String"" MaxLength=""max"" />
      </EntityType>
      <EntityType Name=""Airport"">
        <Key>
          <PropertyRef Name=""IcaoCode"" />
        </Key>
        <Property Name=""IcaoCode"" Type=""Edm.String"" Nullable=""false"" MaxLength=""128"" />
        <Property Name=""Name"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""IataCode"" Type=""Edm.String"" MaxLength=""max"" />
      </EntityType>
      <EntityType Name=""Flight"">
        <Key>
          <PropertyRef Name=""FlightId"" />
        </Key>
        <Property Name=""FlightId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ConfirmationCode"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""StartsAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""EndsAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Duration"" Type=""Edm.Duration"" Nullable=""false"" />
        <Property Name=""SeatNumber"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""FlightNumber"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""FromId"" Type=""Edm.String"" MaxLength=""128"" />
        <Property Name=""ToId"" Type=""Edm.String"" MaxLength=""128"" />
        <Property Name=""AirlineId"" Type=""Edm.String"" MaxLength=""128"" />
        <NavigationProperty Name=""Airline"" Type=""System.Web.OData.Domain.Test.Services.Trippin.Models.Airline"">
          <ReferentialConstraint Property=""AirlineId"" ReferencedProperty=""AirlineCode"" />
        </NavigationProperty>
        <NavigationProperty Name=""From"" Type=""System.Web.OData.Domain.Test.Services.Trippin.Models.Airport"">
          <ReferentialConstraint Property=""FromId"" ReferencedProperty=""IcaoCode"" />
        </NavigationProperty>
        <NavigationProperty Name=""To"" Type=""System.Web.OData.Domain.Test.Services.Trippin.Models.Airport"">
          <ReferentialConstraint Property=""ToId"" ReferencedProperty=""IcaoCode"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""Person"">
        <Key>
          <PropertyRef Name=""PersonId"" />
        </Key>
        <Property Name=""PersonId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""UserName"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""FirstName"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""LastName"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""Concurrency"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""Friends"" Type=""Collection(System.Web.OData.Domain.Test.Services.Trippin.Models.Person)"" />
        <NavigationProperty Name=""Trips"" Type=""Collection(System.Web.OData.Domain.Test.Services.Trippin.Models.Trip)"" />
      </EntityType>
      <EntityType Name=""Trip"">
        <Key>
          <PropertyRef Name=""TripId"" />
        </Key>
        <Property Name=""TripId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PersonId"" Type=""Edm.Int32"" />
        <Property Name=""ShareId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""Budget"" Type=""Edm.Single"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" MaxLength=""max"" />
        <Property Name=""StartsAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""EndsAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""Flights"" Type=""Collection(System.Web.OData.Domain.Test.Services.Trippin.Models.Flight)"" />
      </EntityType>
      <EntityContainer Name=""TrippinModel"">
        <EntitySet Name=""Airlines"" EntityType=""System.Web.OData.Domain.Test.Services.Trippin.Models.Airline"" />
        <EntitySet Name=""Airports"" EntityType=""System.Web.OData.Domain.Test.Services.Trippin.Models.Airport"" />
        <EntitySet Name=""Flights"" EntityType=""System.Web.OData.Domain.Test.Services.Trippin.Models.Flight"">
          <NavigationPropertyBinding Path=""Airline"" Target=""Airlines"" />
          <NavigationPropertyBinding Path=""From"" Target=""Airports"" />
          <NavigationPropertyBinding Path=""To"" Target=""Airports"" />
        </EntitySet>
        <EntitySet Name=""People"" EntityType=""System.Web.OData.Domain.Test.Services.Trippin.Models.Person"">
          <NavigationPropertyBinding Path=""Friends"" Target=""People"" />
          <NavigationPropertyBinding Path=""Trips"" Target=""Trips"" />
        </EntitySet>
        <EntitySet Name=""Trips"" EntityType=""System.Web.OData.Domain.Test.Services.Trippin.Models.Trip"">
          <NavigationPropertyBinding Path=""Flights"" Target=""Flights"" />
        </EntitySet>
        <ActionImport Name=""ResetDataSource"" Action=""System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline.ResetDataSource"" />
      </EntityContainer>
    </Schema>
    <Schema Namespace=""System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""ResetDataSource"" />
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for ResetDataSource in the schema.
        /// </summary>
        public global::Microsoft.OData.Client.DataServiceActionQuery ResetDataSource()
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery(this, this.BaseUri.OriginalString.Trim('/') + "/ResetDataSource");
        }
    }
    /// <summary>
    /// There are no comments for AirlineSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AirlineSingle")]
    public partial class AirlineSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Airline>
    {
        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
    }
    /// <summary>
    /// There are no comments for Airline in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AirlineCode
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("AirlineCode")]
    [global::Microsoft.OData.Client.EntitySet("Airlines")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Airline")]
    public partial class Airline : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Airline object.
        /// </summary>
        /// <param name="airlineCode">Initial value of AirlineCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Airline CreateAirline(string airlineCode)
        {
            Airline airline = new Airline();
            airline.AirlineCode = airlineCode;
            return airline;
        }
        /// <summary>
        /// There are no comments for Property AirlineCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AirlineCode")]
        public string AirlineCode
        {
            get
            {
                return this._AirlineCode;
            }
            set
            {
                this.OnAirlineCodeChanging(value);
                this._AirlineCode = value;
                this.OnAirlineCodeChanged();
                this.OnPropertyChanged("AirlineCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _AirlineCode;
        partial void OnAirlineCodeChanging(string value);
        partial void OnAirlineCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AirportSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AirportSingle")]
    public partial class AirportSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Airport>
    {
        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
    }
    /// <summary>
    /// There are no comments for Airport in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IcaoCode
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("IcaoCode")]
    [global::Microsoft.OData.Client.EntitySet("Airports")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Airport")]
    public partial class Airport : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Airport object.
        /// </summary>
        /// <param name="icaoCode">Initial value of IcaoCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Airport CreateAirport(string icaoCode)
        {
            Airport airport = new Airport();
            airport.IcaoCode = icaoCode;
            return airport;
        }
        /// <summary>
        /// There are no comments for Property IcaoCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IcaoCode")]
        public string IcaoCode
        {
            get
            {
                return this._IcaoCode;
            }
            set
            {
                this.OnIcaoCodeChanging(value);
                this._IcaoCode = value;
                this.OnIcaoCodeChanged();
                this.OnPropertyChanged("IcaoCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _IcaoCode;
        partial void OnIcaoCodeChanging(string value);
        partial void OnIcaoCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property IataCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IataCode")]
        public string IataCode
        {
            get
            {
                return this._IataCode;
            }
            set
            {
                this.OnIataCodeChanging(value);
                this._IataCode = value;
                this.OnIataCodeChanged();
                this.OnPropertyChanged("IataCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _IataCode;
        partial void OnIataCodeChanging(string value);
        partial void OnIataCodeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for FlightSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("FlightSingle")]
    public partial class FlightSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Flight>
    {
        /// <summary>
        /// Initialize a new FlightSingle object.
        /// </summary>
        public FlightSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new FlightSingle object.
        /// </summary>
        public FlightSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Airline in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirlineSingle Airline
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Airline == null))
                {
                    this._Airline = new global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirlineSingle(this.Context, GetPath("Airline"));
                }
                return this._Airline;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirlineSingle _Airline;
        /// <summary>
        /// There are no comments for From in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle From
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._From == null))
                {
                    this._From = new global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle(this.Context, GetPath("From"));
                }
                return this._From;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle _From;
        /// <summary>
        /// There are no comments for To in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle To
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._To == null))
                {
                    this._To = new global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle(this.Context, GetPath("To"));
                }
                return this._To;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle _To;
    }
    /// <summary>
    /// There are no comments for Flight in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FlightId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("FlightId")]
    [global::Microsoft.OData.Client.EntitySet("Flights")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Flight")]
    public partial class Flight : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Flight object.
        /// </summary>
        /// <param name="flightId">Initial value of FlightId.</param>
        /// <param name="startsAt">Initial value of StartsAt.</param>
        /// <param name="endsAt">Initial value of EndsAt.</param>
        /// <param name="duration">Initial value of Duration.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Flight CreateFlight(int flightId, global::System.DateTimeOffset startsAt, global::System.DateTimeOffset endsAt, global::System.TimeSpan duration)
        {
            Flight flight = new Flight();
            flight.FlightId = flightId;
            flight.StartsAt = startsAt;
            flight.EndsAt = endsAt;
            flight.Duration = duration;
            return flight;
        }
        /// <summary>
        /// There are no comments for Property FlightId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FlightId")]
        public int FlightId
        {
            get
            {
                return this._FlightId;
            }
            set
            {
                this.OnFlightIdChanging(value);
                this._FlightId = value;
                this.OnFlightIdChanged();
                this.OnPropertyChanged("FlightId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _FlightId;
        partial void OnFlightIdChanging(int value);
        partial void OnFlightIdChanged();
        /// <summary>
        /// There are no comments for Property ConfirmationCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfirmationCode")]
        public string ConfirmationCode
        {
            get
            {
                return this._ConfirmationCode;
            }
            set
            {
                this.OnConfirmationCodeChanging(value);
                this._ConfirmationCode = value;
                this.OnConfirmationCodeChanged();
                this.OnPropertyChanged("ConfirmationCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _ConfirmationCode;
        partial void OnConfirmationCodeChanging(string value);
        partial void OnConfirmationCodeChanged();
        /// <summary>
        /// There are no comments for Property StartsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StartsAt")]
        public global::System.DateTimeOffset StartsAt
        {
            get
            {
                return this._StartsAt;
            }
            set
            {
                this.OnStartsAtChanging(value);
                this._StartsAt = value;
                this.OnStartsAtChanged();
                this.OnPropertyChanged("StartsAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.DateTimeOffset _StartsAt;
        partial void OnStartsAtChanging(global::System.DateTimeOffset value);
        partial void OnStartsAtChanged();
        /// <summary>
        /// There are no comments for Property EndsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EndsAt")]
        public global::System.DateTimeOffset EndsAt
        {
            get
            {
                return this._EndsAt;
            }
            set
            {
                this.OnEndsAtChanging(value);
                this._EndsAt = value;
                this.OnEndsAtChanged();
                this.OnPropertyChanged("EndsAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.DateTimeOffset _EndsAt;
        partial void OnEndsAtChanging(global::System.DateTimeOffset value);
        partial void OnEndsAtChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Duration")]
        public global::System.TimeSpan Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.TimeSpan _Duration;
        partial void OnDurationChanging(global::System.TimeSpan value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property SeatNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SeatNumber")]
        public string SeatNumber
        {
            get
            {
                return this._SeatNumber;
            }
            set
            {
                this.OnSeatNumberChanging(value);
                this._SeatNumber = value;
                this.OnSeatNumberChanged();
                this.OnPropertyChanged("SeatNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _SeatNumber;
        partial void OnSeatNumberChanging(string value);
        partial void OnSeatNumberChanged();
        /// <summary>
        /// There are no comments for Property FlightNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FlightNumber")]
        public string FlightNumber
        {
            get
            {
                return this._FlightNumber;
            }
            set
            {
                this.OnFlightNumberChanging(value);
                this._FlightNumber = value;
                this.OnFlightNumberChanged();
                this.OnPropertyChanged("FlightNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _FlightNumber;
        partial void OnFlightNumberChanging(string value);
        partial void OnFlightNumberChanged();
        /// <summary>
        /// There are no comments for Property FromId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FromId")]
        public string FromId
        {
            get
            {
                return this._FromId;
            }
            set
            {
                this.OnFromIdChanging(value);
                this._FromId = value;
                this.OnFromIdChanged();
                this.OnPropertyChanged("FromId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _FromId;
        partial void OnFromIdChanging(string value);
        partial void OnFromIdChanged();
        /// <summary>
        /// There are no comments for Property ToId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ToId")]
        public string ToId
        {
            get
            {
                return this._ToId;
            }
            set
            {
                this.OnToIdChanging(value);
                this._ToId = value;
                this.OnToIdChanged();
                this.OnPropertyChanged("ToId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _ToId;
        partial void OnToIdChanging(string value);
        partial void OnToIdChanged();
        /// <summary>
        /// There are no comments for Property AirlineId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AirlineId")]
        public string AirlineId
        {
            get
            {
                return this._AirlineId;
            }
            set
            {
                this.OnAirlineIdChanging(value);
                this._AirlineId = value;
                this.OnAirlineIdChanged();
                this.OnPropertyChanged("AirlineId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _AirlineId;
        partial void OnAirlineIdChanging(string value);
        partial void OnAirlineIdChanged();
        /// <summary>
        /// There are no comments for Property Airline in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Airline")]
        public global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airline Airline
        {
            get
            {
                return this._Airline;
            }
            set
            {
                this.OnAirlineChanging(value);
                this._Airline = value;
                this.OnAirlineChanged();
                this.OnPropertyChanged("Airline");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airline _Airline;
        partial void OnAirlineChanging(global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airline value);
        partial void OnAirlineChanged();
        /// <summary>
        /// There are no comments for Property From in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("From")]
        public global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport From
        {
            get
            {
                return this._From;
            }
            set
            {
                this.OnFromChanging(value);
                this._From = value;
                this.OnFromChanged();
                this.OnPropertyChanged("From");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport _From;
        partial void OnFromChanging(global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport value);
        partial void OnFromChanged();
        /// <summary>
        /// There are no comments for Property To in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("To")]
        public global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport To
        {
            get
            {
                return this._To;
            }
            set
            {
                this.OnToChanging(value);
                this._To = value;
                this.OnToChanged();
                this.OnPropertyChanged("To");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport _To;
        partial void OnToChanging(global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport value);
        partial void OnToChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PersonSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PersonSingle")]
    public partial class PersonSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Person>
    {
        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person> _Friends;
        /// <summary>
        /// There are no comments for Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip> Trips
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Trips == null))
                {
                    this._Trips = Context.CreateQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip>(GetPath("Trips"));
                }
                return this._Trips;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip> _Trips;
    }
    /// <summary>
    /// There are no comments for Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PersonId")]
    [global::Microsoft.OData.Client.EntitySet("People")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Person")]
    public partial class Person : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personId">Initial value of PersonId.</param>
        /// <param name="concurrency">Initial value of Concurrency.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Person CreatePerson(int personId, long concurrency)
        {
            Person person = new Person();
            person.PersonId = personId;
            person.Concurrency = concurrency;
            return person;
        }
        /// <summary>
        /// There are no comments for Property PersonId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PersonId")]
        public int PersonId
        {
            get
            {
                return this._PersonId;
            }
            set
            {
                this.OnPersonIdChanging(value);
                this._PersonId = value;
                this.OnPersonIdChanged();
                this.OnPropertyChanged("PersonId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _PersonId;
        partial void OnPersonIdChanging(int value);
        partial void OnPersonIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Concurrency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Concurrency")]
        public long Concurrency
        {
            get
            {
                return this._Concurrency;
            }
            set
            {
                this.OnConcurrencyChanging(value);
                this._Concurrency = value;
                this.OnConcurrencyChanged();
                this.OnPropertyChanged("Concurrency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private long _Concurrency;
        partial void OnConcurrencyChanging(long value);
        partial void OnConcurrencyChanged();
        /// <summary>
        /// There are no comments for Property Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Friends")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person> Friends
        {
            get
            {
                return this._Friends;
            }
            set
            {
                this.OnFriendsChanging(value);
                this._Friends = value;
                this.OnFriendsChanged();
                this.OnPropertyChanged("Friends");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person> _Friends = new global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFriendsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person> value);
        partial void OnFriendsChanged();
        /// <summary>
        /// There are no comments for Property Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Trips")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip> Trips
        {
            get
            {
                return this._Trips;
            }
            set
            {
                this.OnTripsChanging(value);
                this._Trips = value;
                this.OnTripsChanged();
                this.OnPropertyChanged("Trips");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip> _Trips = new global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTripsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip> value);
        partial void OnTripsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TripSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TripSingle")]
    public partial class TripSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Trip>
    {
        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight> Flights
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Flights == null))
                {
                    this._Flights = Context.CreateQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight>(GetPath("Flights"));
                }
                return this._Flights;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight> _Flights;
    }
    /// <summary>
    /// There are no comments for Trip in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TripId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TripId")]
    [global::Microsoft.OData.Client.EntitySet("Trips")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Trip")]
    public partial class Trip : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Trip object.
        /// </summary>
        /// <param name="tripId">Initial value of TripId.</param>
        /// <param name="shareId">Initial value of ShareId.</param>
        /// <param name="budget">Initial value of Budget.</param>
        /// <param name="startsAt">Initial value of StartsAt.</param>
        /// <param name="endsAt">Initial value of EndsAt.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Trip CreateTrip(int tripId, global::System.Guid shareId, float budget, global::System.DateTimeOffset startsAt, global::System.DateTimeOffset endsAt)
        {
            Trip trip = new Trip();
            trip.TripId = tripId;
            trip.ShareId = shareId;
            trip.Budget = budget;
            trip.StartsAt = startsAt;
            trip.EndsAt = endsAt;
            return trip;
        }
        /// <summary>
        /// There are no comments for Property TripId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TripId")]
        public int TripId
        {
            get
            {
                return this._TripId;
            }
            set
            {
                this.OnTripIdChanging(value);
                this._TripId = value;
                this.OnTripIdChanged();
                this.OnPropertyChanged("TripId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _TripId;
        partial void OnTripIdChanging(int value);
        partial void OnTripIdChanged();
        /// <summary>
        /// There are no comments for Property PersonId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PersonId")]
        public global::System.Nullable<int> PersonId
        {
            get
            {
                return this._PersonId;
            }
            set
            {
                this.OnPersonIdChanging(value);
                this._PersonId = value;
                this.OnPersonIdChanged();
                this.OnPropertyChanged("PersonId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<int> _PersonId;
        partial void OnPersonIdChanging(global::System.Nullable<int> value);
        partial void OnPersonIdChanged();
        /// <summary>
        /// There are no comments for Property ShareId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShareId")]
        public global::System.Guid ShareId
        {
            get
            {
                return this._ShareId;
            }
            set
            {
                this.OnShareIdChanging(value);
                this._ShareId = value;
                this.OnShareIdChanged();
                this.OnPropertyChanged("ShareId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Guid _ShareId;
        partial void OnShareIdChanging(global::System.Guid value);
        partial void OnShareIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Budget in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Budget")]
        public float Budget
        {
            get
            {
                return this._Budget;
            }
            set
            {
                this.OnBudgetChanging(value);
                this._Budget = value;
                this.OnBudgetChanged();
                this.OnPropertyChanged("Budget");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private float _Budget;
        partial void OnBudgetChanging(float value);
        partial void OnBudgetChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property StartsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StartsAt")]
        public global::System.DateTimeOffset StartsAt
        {
            get
            {
                return this._StartsAt;
            }
            set
            {
                this.OnStartsAtChanging(value);
                this._StartsAt = value;
                this.OnStartsAtChanged();
                this.OnPropertyChanged("StartsAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.DateTimeOffset _StartsAt;
        partial void OnStartsAtChanging(global::System.DateTimeOffset value);
        partial void OnStartsAtChanged();
        /// <summary>
        /// There are no comments for Property EndsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EndsAt")]
        public global::System.DateTimeOffset EndsAt
        {
            get
            {
                return this._EndsAt;
            }
            set
            {
                this.OnEndsAtChanging(value);
                this._EndsAt = value;
                this.OnEndsAtChanged();
                this.OnPropertyChanged("EndsAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.DateTimeOffset _EndsAt;
        partial void OnEndsAtChanging(global::System.DateTimeOffset value);
        partial void OnEndsAtChanged();
        /// <summary>
        /// There are no comments for Property Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Flights")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight> Flights
        {
            get
            {
                return this._Flights;
            }
            set
            {
                this.OnFlightsChanging(value);
                this._Flights = value;
                this.OnFlightsChanged();
                this.OnPropertyChanged("Flights");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight> _Flights = new global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFlightsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight> value);
        partial void OnFlightsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airline as global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirlineSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirlineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airline> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirlineSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport as global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Airport> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::System.Web.OData.Domain.Test.Services.Trippin.Models.AirportSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight as global::System.Web.OData.Domain.Test.Services.Trippin.Models.FlightSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::System.Web.OData.Domain.Test.Services.Trippin.Models.FlightSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Flight> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::System.Web.OData.Domain.Test.Services.Trippin.Models.FlightSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person as global::System.Web.OData.Domain.Test.Services.Trippin.Models.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::System.Web.OData.Domain.Test.Services.Trippin.Models.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Person> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::System.Web.OData.Domain.Test.Services.Trippin.Models.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip as global::System.Web.OData.Domain.Test.Services.Trippin.Models.TripSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::System.Web.OData.Domain.Test.Services.Trippin.Models.TripSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::System.Web.OData.Domain.Test.Services.Trippin.Models.Trip> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::System.Web.OData.Domain.Test.Services.Trippin.Models.TripSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace System.Web.OData.Domain.Test.Services.Trippin.DomainPipeline
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
    }
}
