<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0;</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<OutputType>exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Microsoft.Restier.Core\Microsoft.Restier.Core.csproj" />
		<ProjectReference Include="..\Microsoft.Restier.Tests.Shared\Microsoft.Restier.Tests.Shared.csproj" />
	</ItemGroup>
</Project>
